version: '3'

services:

    app:
        build: 
            context: .
            dockerfile: Dockerfile.dev
        container_name: laravel-queue-app
        entrypoint: dockerize -wait tcp://db:3306 -timeout 40s ./.docker/entrypoint.sh
        volumes:
            - .:/var/www
        depends_on:
            - db
    
    queue:
        build: ./.docker/queue
        container_name: laravel-queue-queue
        volumes:
            - .:/var/www
        depends_on:
            - db

    nginx:
        build: .docker/nginx
        container_name: laravel-queue-nginx
        restart: always
        tty: true
        ports:
            - "8000:80"
        volumes:
            - .:/var/www
        depends_on:
            - app

    db:
        build: ./.docker/mysql
        container_name: laravel-queue-db
        restart: always
        tty: true
        ports:
            - "33006:3306"
        volumes:
            - ./.docker/dbdata:/var/lib/mysql
        environment:
            - MYSQL_DATABASE=laravel_queue
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_USER=root
